### PR TITLE
Change configuration method

### PR DESCRIPTION
**Pull request by kuggenhoffen**
* Move configuration parameter resolution to separate header
* Allow user definable configuration header to be included

### CODE REVIEW

**Comment by kuggenhoffen** [comment]
@kjbracey-arm @SeppoTakalo @yogpan01 @TeroJaasko 
For easier configuration of different platforms and build systems I moved all the config parameter resolving to own header file and added possibility to define user provided configuration header.

**Comment by TeroJaasko** [comment]
I guess this is missing the part which allows one to use "user definable configuration header"?

On mbedtls one can supply the "-DMBEDTLS_CONFIG_FILE='<foo.h>'" " to compiler and the MBEDTLS_CONFIG_FILE is used on the #include line. See the end of https://github.com/ARMmbed/mbedtls/blob/development/include/mbedtls/config.h.

**Comment by kjbracey-arm** [comment]
Fine with the concept, as long as you don't use the facility to reconfigure on mbed OS or any system with a real config system.

(But you could conceivably make it point at a "universal" mbed OS header file which picks up all options from the mbed config system, thus pulling those tests out of the main one).

**Comment by kuggenhoffen** [comment]
@TeroJaasko user configurable header is included at end of eventloop_config.h

**Comment by TeroJaasko** [comment]
@kuggenhoffen thanks, I'll get my coat.

**Comment by kuggenhoffen** [comment]
@kjbracey-arm Yes, idea was that on mbedOS (and others with configuration system) the "native" configuration system parameters (MBED_CONF_*) will map to internal macros (NS_*) in eventloop_config.h while on systems with no native configuration method the config header include will be used to define the internal macros.

I suppose with this implementation it's still possible to provide the config file in mbed OS as well if someone really wanted but I don't think that would be intended use case.

**Comment by kjbracey-arm** [comment]
That's fine. I just have nightmares about people having a mbed_lib.json that has no real mbed TLS configuration options but merely lets you point to a different config file.

(Exactly as mbed TLS is at the minute, in fact.)

**Pull request merged**
