### PR TITLE
Fhss dev2

### PR DESCRIPTION
**Pull request by TeroJaasko**
@JarkkoPaso @juhhei01 @mikter @kjbracey-arm @SeppoTakalo @artokin

### CODE REVIEW

**Comment by kjbracey-arm** [comment]
Could we rebase it so it isn't 2 real commits and 7 noise commits?

**Comment by kjbracey-arm** [comment]
Note we're in the silly situation where we've got duplicated files between "source" and "bare-metal". This is marginally less silly than the previous situation where we had slightly different copies, but still annoying.

You need to keep both copies in sync - "source" is being used by Yotta, "bare-metal" by makefiles.

**Comment by SeppoTakalo** [comment]
Is this valid anymore?
Can I close this?

**Comment by JarkkoPaso** [comment]
@SeppoTakalo Yes, I think this can be closed

**Pull request closed without merging**
