### PR TITLE
Add event loop mutex API

### PR DESCRIPTION
**Pull request by kjbracey-arm**
Provide a generic mechanism for mutexing threads against the event loop,
on multi-threaded systems. No implementation provided - this goes
straight to the platform layer.

### CODE REVIEW

**Comment by kjbracey-arm** [comment]
@SeppoTakalo, @juhhei01, @mikter, @yogpan01, @TeroJaasko

**Comment by TeroJaasko** [comment]
+1.

**Comment by SeppoTakalo** [comment]
+1,
is this going to replace the `system_enter_critical()` call on the event-loop side?

**Comment by kjbracey-arm** [comment]
This is not a replacement for platform_enter_critical(). That is a "lower-level" lock - effectively protection against the driver context. Either interrupt disable or a mutex, depending on how the driver works. 

This is for protection amongst application contexts - threads making the claim will mutex against the event loop thread, and only run when the event loop is idle. It will allow you to serialise Nanostack and other code like mbed-client, in a multithreaded environment.

**Pull request merged**
